<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>

<h1>News</h1>
<div>
    <hr>
    <div class="news preview">
        <br>
        <h2 class="center-text">Season 2018</h2>
        <img class="center" src="https://www.valais.ch/media/cache/lightbox/c/ChaletKerst_ret.jpg" alt="Site is now available">
    </div>
    <hr>
    <div class="news preview">
        <br>
        <h2 class="center-text">Updated Website</h2>
        <img class="center" src="https://www.valais.ch/media/cache/lightbox/2/2016_Hiver_Ski-et-Snowboard_%28c%29-Valais_Wallis-Promotion---David-Carlier-%2831%29_Hors-piste-au-pied-du-Bec-des-Rosses-a-Verbier.jpg" alt="Valais">
    </div>
</div>